server.port=8080
server.servlet.context-path=/

vk.access.token=vk1.a.p9PA3JDq5XOK72ZiNmXpO5YtmPSlVA6DKUOf876ftdeprQnm02dgHu6fcxXQ9xtwSXBvUA7K9NeCJlNNOTjMU0ppK_rHYDeJW_cVQcfktu7eeA0qwgkm5d_xr19yBm0owN-wVc7syGLZNgtGDWfCqA7gPtoVSwi7HFZUMyUBHHo8Plw1PYQNcsnbL-2rAzgm2z4aWdTnLUH2gVw6mE0syg
vk.group.id=154968615
vk.album.id=277461398
vk.photos.count=1000
upload.max-file-size=10MB


logging.level.org.example.thoughts=DEBUG