server.port=8080
server.servlet.context-path=/

vk.access.token=${VK_ACCESS_TOKEN}
vk.group.id=154968615
vk.album.id=277461398
vk.photos.count=1000
service.api-key=${INTERNAL_API_KEY}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


logging.level.org.example.thoughts=INFO
